set(SOURCE_FILES
    block-encode-test.cpp
    block-decode-test.cpp
    decode-test.cpp
    encode-test.cpp
    header-test.cpp
    options-decode-test.cpp
    options-encode-test.cpp
    uint-test.cpp
)
